env: "local"
database:
  db_username: "postgres"
  db_password: "postgres"
  db_name: "tabhub"
  db_host: "localhost"
  db_port: 5432
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
