env: "local"

database:
  db_username: "postgres"
  db_password: "postgres"
  db_name: "tabhub"
  db_host: "localhost"
  db_port: 5432

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

cache:
  cache_address: "localhost:6379"
  cache_user: "redis"
  cache_password: "redis"
  cache_db: 0
  cache_timeout: 5s